-- v0.42.0 migration delta ONLY. Adds the `locked_shots_json` column to
-- the renders table so the planner UI can persist per-shot lock state
-- (the "approved" marker a user sets between previewing keyframes and
-- finalizing). NULL = nothing locked. The column stores a JSON array of
-- shot_id strings; the row normalizer parses it back at read time and
-- drops malformed entries silently.
--
-- The GPU side (vivijure-serverless 0.4.4) is NOT informed of this
-- field: lock state is metadata-only in v0.42.0, finalize runs Wan
-- I2V + assemble over every shot regardless of lock. A future commit
-- may make lock state actually gate selective rendering (skip / keep
-- per shot), at which point we will pass it through render_overrides.
--
-- Idempotent caveat: SQLite's ALTER TABLE ADD COLUMN is NOT idempotent;
-- re-running this against an already-migrated DB surfaces "duplicate
-- column name" which wrangler d1 execute treats as a non-fatal warning
-- and continues past. Same pattern as the v0.36 / v0.39 / v0.40 ALTERs.
--
-- Apply: wrangler d1 execute skyphusion-llm --remote --file=migrate-v0.42.0.sql

ALTER TABLE renders ADD COLUMN locked_shots_json TEXT;
